version: '3'
services:
    redis:
        image: redis:alpine
        command: redis-server --requirepass local_dev_redis_password
        expose: 
            - 6379
        volumes:
            - $PWD/redis-data:/var/lib/redis
        environment:
            - REDIS_REPLIACTION_MODE=master
    web:
        #depends_on: 
        #    - redis
        build: .
        image: algothon-web
        ports:
            - "8080:8080"
        environment:
            - SESSION_KEY=local_dev_session_key
            - SALT=local_dev_salt
            - REDIS_PASSWORD=local_dev_redis_password
        command:
            - --log_level=DEBUG